// Slide deck for the "Platform engineering" stage talk. The talk positions the
// government as the largest software shop in the country; "Begane Grond" (the
// demo app) is the running example used to make that concrete. The left rail
// (the deck) tells the story; the right side drives the live demo app to the
// matching route, optionally emits an event, runs a wizard, or highlights part
// of the screen.
//
// Each slide is a plain data object consumed by the presentation overlay:
//   {
//     id,                  // stable string key
//     title,               // slide heading (Dutch UI string)
//     lead?,               // one-line framing under the title (Dutch)
//     bullets: [...],      // short persuasive points (Dutch)
//     gov?,                // government-specific callout (Dutch), shown apart
//     route?,              // demo route to navigate to (router.push)
//     emit?,               // { type, title, severity? } -> store.emit(...)
//     drive?,              // { wizard: 'order'|'app'|'wet'|'werkplek'|
//                          //   'promotie'|'campagne'|'llm'|'cert' } auto-run flow
//     highlight?,          // CSS selector to pulse on the demo side
//     link?,               // { href, label } shown as a closing link on the slide
//     speaker?,            // presenter name (title slide)
//     affiliation?,        // presenter affiliation (title slide)
//     showDate?,           // render today's date on the slide (title slide)
//     full?,               // full-width intro/closing slide (no left rail)
//     skippable?,          // mark as optional, cut first when running short
//   }
//
// The story builds from basic, standard platform functionality (paved paths,
// self-service, the stack, build and CI) up through operating and securing it,
// and only then into the government-specific layers (basisregistraties, data
// quality, law as code, the mandatory registers). That arc is deliberate: the
// audience first sees a platform any modern software shop would recognize, then
// the parts that are unique to running the state.
//
// All UI text is Dutch; identifiers and comments are English. No clock or
// random APIs are used here (the codebase forbids them); the deck is fully
// static data.

export const slides = [
  {
    id: 'titel',
    title: 'Platform engineering',
    lead: 'Waarom de Nederlandse overheid misschien wel het grootste softwarebedrijf van Nederland is. En waarom we ons ook zo moeten organiseren.',
    speaker: 'Anne Schuth',
    affiliation: 'Nederlandse Digitale Dienst',
    showDate: true,
    route: '/',
    full: true,
  },
  {
    id: 'overheid-techbedrijf',
    title: 'De overheid is een techbedrijf',
    lead: 'Het grootste en meest complexe softwarebedrijf van Nederland. Alleen noemt niemand het zo.',
    bullets: [
      'Belasting, toeslagen, uitkeringen, paspoorten: dat is software, op enorme schaal.',
      'De Belastingdienst verwerkt jaarlijks meer dan 10 miljoen aangiftes, met honderden wijzigingen per jaar.',
      'Er is geen kant-en-klaar product voor de Toeslagenberekening. Je kunt het niet kopen.',
    ],
    emit: { type: 'deploy.completed', title: 'app-toeslagen v2.3.9 uitgerold naar productie' },
    full: true,
  },
  {
    id: 'uitbesteden-vastloopt',
    title: 'Inkopen werkt niet',
    lead: 'De klassieke route is een groot traject uitbesteden. Bij software op deze schaal loopt dat keer op keer vast.',
    bullets: [
      'Twee op de drie grote IT-projecten van de overheid lopen vertraging op.',
      'Miljarden aan budgetoverschrijding, en dan werkt het vaak nog niet.',
      'De wereld is te ingewikkeld om vooraf dicht te timmeren in een bestek.',
      'Vendor lock-in: eenmaal binnen kom je er niet meer uit.',
    ],
    emit: {
      type: 'deploy.failed',
      title: 'Groot inkooptraject opnieuw vertraagd',
      severity: 'critical',
    },
    full: true,
  },
  {
    id: 'ai-kantelt',
    title: 'AI kantelt koop versus bouw',
    lead: 'Code wordt goedkoop. Dat verandert de rekensom.',
    bullets: [
      'Wat je vroeger kocht omdat zelf bouwen te duur was, bouw je nu zelf.',
      'AI-assistentie maakt een klein team verrassend productief.',
      'Maar goedkope code zonder platform is een berg techniek-schuld in wording.',
    ],
    emit: { type: 'ai.skill.installed', title: 'AI-assistent geactiveerd voor het team' },
    full: true,
  },
  {
    id: 'voorbeeld-begane-grond',
    title: 'Een voorbeeld: Begane Grond',
    lead: 'Om concreet te maken wat ik bedoel, lopen we door één platform heen.',
    bullets: [
      'Begane Grond: een ontwikkelplatform voor de Rijksoverheid.',
      'Je bouwt de begane grond op het fundament.',
      'Dat fundament is een soevereine cloud voor het Rijk, waar we nu aan werken.',
      'Let op: dit is een demo, een proof of concept, om het gesprek te kunnen voeren.',
    ],
    route: '/',
    highlight: '.rp-page',
  },
  {
    id: 'geplaveide-weg',
    title: 'Het gebaande pad',
    lead: 'Gebaande paden: de makkelijke route is meteen de juiste route.',
    bullets: [
      'Begin niet bij een leeg scherm, maar bij een werkend startpunt.',
      'Nu duurt het 93 dagen om een nieuwe dienst in productie te krijgen.',
      'Met een platform eronder: minuten in plaats van maanden.',
    ],
    route: '/apps/templates',
    emit: { type: 'repo.created', title: 'Nieuwe dienst opgezet via gebaand pad' },
  },
  {
    id: 'design-system',
    title: 'Eén design system',
    lead: 'Het gebaande pad voor de interface: toegankelijkheid en huisstijl als bouwblok.',
    bullets: [
      'Teams bouwen geen eigen knop of formulier, ze nemen het over en bouwen verder.',
      'Toegankelijkheid (WCAG 2.2 AA) zit in de componenten, niet in een audit achteraf.',
      'Dogfooding: deze hele demo en deze slides draaien er zelf op. Je kijkt er nu naar.',
    ],
    gov: 'Eén herkenbare rijkshuisstijl voor elke dienst, zodat de burger de overheid herkent.',
    route: '/design-system',
    highlight: '.rp-page',
  },
  {
    id: 'self-service',
    title: 'Self-service',
    lead: 'Zelf afnemen, niet wachten op een ander team.',
    bullets: [
      'Een database nodig? Bestel hem zelf, hij staat er binnen minuten.',
      'Geen ticket, geen wachtrij, geen e-mail naar beheer.',
      'Op Spotify waren teams met een platform eronder 2,3 keer zo actief, met dezelfde mensen.',
    ],
    route: '/infra',
    emit: { type: 'infra.instance.requested', title: 'PostgreSQL aangevraagd uit de catalogus' },
  },
  {
    id: 'gelaagde-stack',
    title: 'De gelaagde stack',
    lead: 'Alles hangt samen, van persoon tot ijzer.',
    bullets: [
      'Persoon, team, applicatie, instance, rack, datacenter.',
      'Elke laag is zichtbaar en herleidbaar, geen blinde vlekken.',
      'Klik op een app en je ziet tot in welk rack hij draait.',
    ],
    route: '/',
    highlight: '.rp-page',
    skippable: true,
  },
  {
    id: 'fysiek-ijzer',
    title: 'Fundament: het ijzer',
    lead: 'Onder de software staat echte hardware.',
    bullets: [
      'Eigen datacenters, geen black box bij een onbekende leverancier.',
      'Je kunt het rack aanwijzen waarin de dienst draait.',
      'De basis is van onszelf, dus controle blijft binnen.',
    ],
    gov: 'Data blijft in Nederland. Soevereiniteit begint bij het ijzer dat je zelf bezit.',
    route: '/fysiek',
    emit: { type: 'capacity.warning', title: 'Datacenter Den Haag: 78% rackcapaciteit' },
    skippable: true,
  },
  {
    id: 'tot-in-het-rack',
    title: 'Tot in het rack',
    lead: 'Van een abstract dienstje naar een concrete plek in een kast.',
    bullets: [
      'Elke unit in het rack is bekend en gekoppeld aan een dienst.',
      'Storing? Je weet meteen welke hardware en welk team erbij hoort.',
      'Transparantie van wettekst tot stroomstekker.',
    ],
    route: '/fysiek/racks/r-dh-a1',
    emit: { type: 'cooling.alert', title: 'Rack r-dh-a1: koeling binnen marge' },
    skippable: true,
  },
  {
    id: 'infra-afnemen',
    title: 'Infra afnemen, live',
    lead: 'Een database bestellen, voor uw ogen.',
    bullets: [
      'Kies de dienst, vul wat in, bevestig.',
      'Geen formulier dat ergens in een postbus belandt.',
      'Let op de bel rechtsboven als de instance gereed is.',
    ],
    route: '/infra/order/postgres',
    drive: { wizard: 'order' },
    emit: { type: 'infra.instance.ready', title: 'Demo-instance is gereed' },
  },
  {
    id: 'applicaties',
    title: 'Applicaties',
    lead: 'De diensten die burgers en ambtenaren echt gebruiken.',
    bullets: [
      'Elke applicatie heeft een eigenaar, een team en een herkomst.',
      'Geen schaduw-IT, geen verweesde systemen meer.',
      'Eén catalogus voor alles wat er draait.',
    ],
    route: '/apps',
    emit: { type: 'app.created', title: 'Nieuwe applicatie geregistreerd in de catalogus' },
  },
  {
    id: 'nieuwe-app',
    title: 'Nieuwe app via het gebaande pad',
    lead: 'Van niets naar een werkend project, live.',
    bullets: [
      'Kies een gebaand pad en de rest staat klaar.',
      'Repository, pipeline en standaarden zitten er al in.',
      'De makkelijke keuze is meteen de veilige keuze.',
    ],
    route: '/apps/nieuw',
    drive: { wizard: 'app' },
  },
  {
    id: 'code-forgejo',
    title: 'Code op Forgejo',
    lead: 'De broncode draait op eigen grond.',
    bullets: [
      'Eén plek voor alle repositories van het Rijk.',
      'Pull requests, reviews en geschiedenis, volledig in eigen beheer.',
      'Open waar het kan, dicht waar het moet.',
    ],
    gov: 'Open-tenzij, op een eigen forge. Geen broncode in een buitenlandse cloud, soevereiniteit by design.',
    route: '/code',
    emit: { type: 'pr.opened', title: 'Pull request geopend op code.overheid.nl' },
  },
  {
    id: 'cli-rp',
    title: 'De CLI: bg',
    lead: 'Het hele platform in één commando.',
    bullets: [
      'Alles wat je klikt kun je ook scripten.',
      'Voor wie liever in de terminal woont dan in een dashboard.',
      'Eén tool die het gebaande pad in tekstvorm geeft.',
    ],
    route: '/cli',
    emit: { type: 'repo.created', title: 'Repository aangemaakt via bg new' },
    skippable: true,
  },
  {
    id: 'ci-runners',
    title: 'CI-runners',
    lead: 'De machines die de code bouwen en testen.',
    bullets: [
      'Elke wijziging wordt automatisch gebouwd en gecontroleerd.',
      'Capaciteit die je deelt in plaats van per team opnieuw optuigt.',
      'De lopende band onder het gebaande pad.',
    ],
    route: '/environments/runners',
    emit: { type: 'runner.scaled', title: 'Runner-pool opgeschaald naar de wachtrij' },
    skippable: true,
  },
  {
    id: 'pijplijn-by-default',
    title: 'Eén pijplijn, by default',
    lead: 'Alles wat een team normaal uit losse systemen haalt, zit hier in één gebaand pad.',
    bullets: [
      'Code, CI, kwaliteit, coverage, dependencies, kwetsbaarheden en artefacten in één pad.',
      'Niet zelf bekabelen per team. Standaard aan op elke repository.',
      'De gates draaien in elke pijplijn, ook als niemand naar een dashboard kijkt.',
    ],
    gov: 'Kwaliteit en compliance als default, niet als losse tool die je hoopt dat iemand bezoekt.',
    route: '/environments/pijplijn',
    emit: { type: 'pipeline.passed', title: 'Pijplijn groen, alle gates gehaald' },
  },
  {
    id: 'promoten',
    title: 'Promoten met gates, live',
    lead: 'Een release een stap opschuiven, met de controles erbij.',
    bullets: [
      'Van acceptatie naar productie, maar alleen als de gates groen zijn.',
      'Tests, security en een goedgekeurde wijziging worden afgevinkt.',
      'De pijplijn bouwt, test, scant en deployt voor je ogen.',
    ],
    gov: 'Kwaliteit en governance als afdwingbare gates, niet als handtekening op een formulier.',
    route: '/environments/promotie/app-toeslagen',
    drive: { wizard: 'promotie' },
  },
  {
    id: 'infra-als-code',
    title: 'En dat was een commit',
    lead: 'Die promotie was geen losse klik: het werd een diff in git, een nieuwe gewenste versie.',
    bullets: [
      'Elke wizard en elke knop schrijft naar één config-repo, ook deze promotie.',
      'Je kunt altijd naar de onderliggende code kijken, en elke wijziging terugdraaien.',
      'Desired state staat in git; drift is zichtbaar als afwijking daarvan.',
    ],
    gov: 'Herleidbaar en reproduceerbaar van nature: precies wat een overheid moet kunnen aantonen.',
    route: '/platform/iac',
    highlight: '.rp-page',
    emit: { type: 'config.committed', title: 'Commit op platform-config: nieuwe gewenste versie' },
  },
  {
    id: 'artefacten',
    title: 'Artefacten, SBOM en handtekeningen',
    lead: 'Elk gebouwd artefact heeft een paklijst en een handtekening.',
    bullets: [
      'Een SBOM bij elke build: je weet precies wat erin zit.',
      'Gesigneerd en herleidbaar tot de commit die het maakte.',
      'Bij een nieuwe kwetsbaarheid zie je meteen welke diensten geraakt zijn.',
    ],
    gov: 'Transparantie in de toeleveringsketen als default. Bij een CVE is de impact in seconden bekend, niet na weken zoeken.',
    route: '/artefacten',
    emit: { type: 'scan.completed', title: 'SBOM gegenereerd en artefact gesigneerd' },
    highlight: '.rp-page',
    skippable: true,
  },
  {
    id: 'teams-oncall',
    title: 'Teams, mensen en on-call',
    lead: 'Achter elke dienst staan mensen.',
    bullets: [
      'Een matrix die laat zien wie waarvoor bereikbaar is.',
      'Geen losse telefoonlijst in een la, maar onderdeel van het platform.',
      'Goed gereedschap trekt goed vakmanschap aan.',
    ],
    route: '/teams/on-call',
    emit: { type: 'oncall.handover', title: 'On-call overgedragen aan het volgende team' },
    skippable: true,
  },
  {
    id: 'werkplek-uitrollen',
    title: 'Werkplek uitrollen, live',
    lead: 'Een nieuwe collega, op dag één productief.',
    bullets: [
      'Kies de medewerker, het toestel en het profiel.',
      'Versleuteld en MDM-beheerd, want de BIO schrijft het voor.',
      'Van bestelling tot werkende laptop, in één doorlopende stroom.',
    ],
    gov: 'Encryptie en MDM staan standaard aan. De Rijksbaseline is ingebouwd, niet optioneel.',
    route: '/werkplekken/nieuw',
    drive: { wizard: 'werkplek' },
    skippable: true,
  },
  {
    id: 'observability',
    title: 'Observability',
    lead: 'Zien wat er gebeurt, voordat een burger het merkt.',
    bullets: [
      'Logs, metrics en traces op één plek.',
      'Niet gokken bij een storing, maar kijken.',
      'Inzicht standaard aan, niet als duur achteraf-project.',
    ],
    route: '/observability',
    emit: { type: 'alert.firing', title: 'SLO-alert: latency boven de drempel' },
    skippable: true,
  },
  {
    id: 'incident',
    title: 'Incident, live',
    lead: 'Er gaat nu iets mis. Expres.',
    bullets: [
      'Verhoogde latency op productie, en het platform weet het meteen.',
      'De bel rechtsboven kleurt rood.',
      'Wie, wat en waar staan direct klaar voor wie het oppakt.',
    ],
    route: '/incidenten',
    emit: {
      type: 'incident.opened',
      title: 'Verhoogde latency op productie',
      severity: 'critical',
    },
  },
  {
    id: 'finops',
    title: 'FinOps: kosten',
    lead: 'Wat het kost en aan wie het toe te rekenen is.',
    bullets: [
      'Kosten per team zichtbaar, niet pas op de jaarrekening.',
      'Zelf afnemen betekent ook zelf de rekening zien.',
      'Sturen op geld zonder de innovatie af te knijpen.',
    ],
    route: '/kosten',
    emit: { type: 'cost.anomaly', title: 'Kostenanomalie gedetecteerd bij een team' },
    skippable: true,
  },
  {
    id: 'software-inkoop',
    title: 'Koop of bouw, met een uitweg',
    lead: 'Wat je toch inkoopt, koop je met het lock-in-risico en de exit-strategie erbij.',
    bullets: [
      'Niet alles bouw je zelf. Wat je koopt, leg je vast met voorwaarden en een uitweg.',
      'Per contract staat het lock-in-risico en hoe je eruit stapt.',
      'Open source verlaagt de afhankelijkheid, en dat is zichtbaar te sturen.',
    ],
    gov: 'Afhankelijkheid van een leverancier wordt een bewuste, herleidbare keuze onder ARBIT en ARVODI, geen sluipend gevolg.',
    route: '/software-inkoop',
    highlight: '.rp-page',
    skippable: true,
  },
  {
    id: 'security-compliance',
    title: 'Security en compliance',
    lead: 'Veiligheid is geen bijlage achteraf.',
    bullets: [
      'Niet een PDF over TLS 1.3, maar de platform-default.',
      'Afgedwongen via pull requests, niet via goede voornemens.',
      'Eenmaal goed ingeregeld, voor iedereen tegelijk.',
    ],
    gov: 'BIO als default. Compliance ingebakken in het gebaande pad, niet als bijlage bij een rapport.',
    route: '/security',
    emit: { type: 'compliance.dropped', title: 'Compliance-score gedaald, actie vereist' },
  },
  {
    id: 'standaarden',
    title: 'Standaarden',
    lead: 'Standaard als code, afgedwongen via pull requests.',
    bullets: [
      'NLDD design system, API Design Rules, internet.nl.',
      'WCAG 2.2 AA en BIO, niet als wens maar als check.',
      'Wat nu inconsistent is, embed je één keer als default.',
    ],
    gov: 'Open standaarden van de Rijksoverheid, eenmalig ingebouwd en overal afgedwongen.',
    route: '/standaarden',
    emit: { type: 'standard.updated', title: 'NLDD design system bijgewerkt naar 0.9' },
    highlight: '.rp-page',
  },
  // --- NeRDS-ronde: het charter als rode draad door het hele platform. ---
  {
    id: 'nerds-intro',
    title: 'NeRDS als rode draad',
    lead: 'De Nederlandse Richtlijn Digitale Systemen: dertien richtlijnen voor verantwoord bouwen. Geen los bouwblok dat je installeert, maar een lens over alles wat er al staat.',
    bullets: [
      'Elke richtlijn heeft al een plek in Begane Grond, van gebruikersbehoeften tot duurzaamheid.',
      'Per richtlijn zie je hoeveel van de vloot er al aan voldoet.',
      'De volgende minuten lopen we langs het charter en langs wat het op de plek zelf zichtbaar maakt.',
    ],
    gov: 'Niet één bouwblok, maar een lens over alles: één raamwerk voor verantwoorde digitale systemen.',
    link: { href: 'https://minbzk.github.io/NeRDS/', label: 'minbzk.github.io/NeRDS' },
    route: '/nerds',
    highlight: '.rp-pillars',
    full: true,
  },
  {
    id: 'nerds-badge-veiligheid',
    title: 'Op de plek zelf zichtbaar',
    lead: 'Een richtlijn leeft niet op een aparte pagina. Op het securityscherm staat het er gewoon: hiermee voldoe je aan NeRDS-richtlijn 6, Veiligheid.',
    bullets: [
      'De badge linkt het scherm aan de richtlijn die het invult, geen losse checklist ernaast.',
      'Het oordeel erft de bestaande BIO-gate, dus dit klopt met governance en security.',
      'Klik de badge, en je staat op de juiste kaart in het charter.',
    ],
    gov: 'De richtlijn wordt zichtbaar waar het werk gebeurt, niet in een apart compliance-document.',
    route: '/security',
    highlight: '.rp-nerds-badge',
    emit: { type: 'standard.updated', title: 'NeRDS-richtlijn Veiligheid: voldaan' },
  },
  {
    id: 'nerds-badge-toegankelijkheid',
    title: 'Dezelfde draad, andere richtlijn',
    lead: 'Hetzelfde geldt voor toegankelijkheid: hiermee voldoe je aan NeRDS-richtlijn 2.',
    bullets: [
      'Dezelfde badge, nu op de toegankelijkheidsverklaringen, gevoed door de WCAG-gate.',
      'Dertien richtlijnen, dertien plekken waar het werk al gebeurt.',
    ],
    gov: 'Eén consistent merk door het hele platform: hier draag je bij aan NeRDS.',
    route: '/toegankelijkheid',
    highlight: '.rp-nerds-badge',
    skippable: true,
  },
  {
    id: 'nerds-scorecard',
    title: 'Per app: hoeveel van de dertien',
    lead: 'De badges rollen op tot één scorecard per applicatie en over de hele vloot. Een eerlijke N van de 13, geen metaalkleur.',
    bullets: [
      'De oordelen komen uit de bestaande gates, checks en standaarden, niet uit een tweede waarheid.',
      'Een open richtlijn linkt door naar de plek waar je het oplost.',
      'Zo wordt het charter meetbaar zonder dat iemand het apart hoeft bij te houden.',
    ],
    gov: 'Verantwoording die volgt uit het platform zelf, in plaats van een losse jaarlijkse rapportage.',
    route: '/nerds/scorecard',
    highlight: '.rp-page',
    emit: { type: 'standard.updated', title: 'NeRDS-scorecard bijgewerkt over de vloot' },
  },
  {
    id: 'inloggen',
    title: 'Inloggen voor burger en ambtenaar',
    lead: 'DigiD en eHerkenning als gebaand pad, niet als koppelproject per dienst.',
    bullets: [
      'Eén ingang voor authenticatie, hergebruikt door elke dienst.',
      'Het niveau van zekerheid past zich aan de dienst aan.',
      'Geen eigen wachtwoordendoosje per applicatie meer.',
    ],
    gov: 'DigiD en eHerkenning zijn verplicht. Het platform levert ze als dienst, niet als losse integratie per project.',
    route: '/inloggen',
    emit: { type: 'register.connected', title: 'Dienst aangesloten op DigiD' },
    highlight: '.rp-page',
  },
  {
    id: 'dns',
    title: 'Domeinen en DNS, met DNSSEC aan',
    lead: 'Een overheid.nl-domein aanvragen met de beveiliging meteen goed.',
    bullets: [
      'DNSSEC, SPF en DMARC staan standaard aan, niet als nazorg.',
      'Eén plek voor alle domeinen van het Rijk, geen vergeten registraties.',
      'Wat internet.nl test, levert het platform al ingebouwd.',
    ],
    gov: 'De open internetstandaarden van Forum Standaardisatie als default op elk overheidsdomein.',
    route: '/dns',
    emit: { type: 'standard.updated', title: 'DNSSEC ingeschakeld op nieuw domein' },
    highlight: '.rp-page',
  },
  {
    id: 'certificaten',
    title: 'Een certificaat in seconden, live',
    lead: 'Een PKIoverheid-certificaat was weken handwerk. Nu een gebaand pad dat zichzelf vernieuwt.',
    bullets: [
      'Vroeger: zelf een CSR maken, aanvragen bij een TSP, wachten, handmatig installeren.',
      'En dan de vernieuwing vergeten, waardoor de dienst omvalt.',
      'Nu: een aanvraag, automatisch uitgegeven en gekoppeld, auto-vernieuwing standaard aan.',
    ],
    gov: 'PKIoverheid van papieren proces naar self-service. Verlopen door vergeten kan niet meer.',
    route: '/secrets/certificaten',
    drive: { wizard: 'cert' },
  },
  {
    id: 'fleet-campagne',
    title: 'Eén wijziging, hele vloot, live',
    lead: 'Een nieuwe standaard uitrollen over alle repositories tegelijk.',
    bullets: [
      'Beschrijf de wijziging één keer, het platform opent overal een pull request.',
      'Een versie-bump of een security.txt, in honderden repos in één keer.',
      'Zo wordt een standaard echt afgedwongen, niet alleen opgeschreven.',
    ],
    gov: 'Een beleidswijziging wordt een codewijziging die je over de hele Rijksvloot uitrolt.',
    route: '/fleet/nieuw',
    drive: { wizard: 'campagne' },
  },
  {
    id: 'basisregistraties',
    title: 'Basisregistraties',
    lead: 'De bronnen van waarheid van de overheid.',
    bullets: [
      'BRP, BRK, BAG, HR en het Kentekenregister, ontsloten via één laag.',
      'Identificatie via OIN en TOOI, herkomst altijd traceerbaar.',
      'Niet zelf data overtikken, maar bevragen bij de bron.',
    ],
    gov: 'AVG-proof bevragen: alleen wat mag, met OIN-authenticatie en een spoor terug naar de bron.',
    route: '/registers',
    emit: { type: 'register.connected', title: 'Dienst aangesloten op de BRP' },
    highlight: '.rp-page',
  },
  {
    id: 'datakwaliteit',
    title: 'Datakwaliteit met labels',
    lead: 'Niet alleen waar de data vandaan komt, maar ook hoe goed die is. Goud, zilver, brons.',
    bullets: [
      'Elke dataset krijgt een kwaliteitslabel op volledigheid, actualiteit en herleidbaarheid.',
      'Open tenzij: standaard openbaar, gesloten alleen met reden.',
      'Lineage van wet tot dataset tot dienst, in één klik te volgen.',
    ],
    gov: 'Herleidbaarheid is een wettelijke eis, geen extraatje. Het label maakt zichtbaar of een bron geschikt is voor een besluit.',
    route: '/data',
    highlight: '.rp-page',
  },
  {
    id: 'datacontracten',
    title: 'Datacontracten',
    lead: 'Een dataset delen met een contract erop: wie mag wat, hoe vers, met welke garantie.',
    bullets: [
      'Niet ad-hoc een export mailen, maar een afdwingbaar contract tussen aanbieder en afnemer.',
      'Versheid, schema en toegang staan vast en worden bewaakt.',
      'Breekt de leverancier het schema, dan weet de afnemer het meteen.',
    ],
    gov: 'Gegevensdeling met afspraken die het platform handhaaft, niet met goede bedoelingen.',
    route: '/datacontracten',
    emit: {
      type: 'register.connected',
      title: 'Datacontract geactiveerd tussen aanbieder en afnemer',
    },
    highlight: '.rp-page',
    skippable: true,
  },
  // --- Haven(+) ronde: een tour langs het label en wat het invult. ---
  {
    id: 'haven-intro',
    title: 'Haven: één keer bouwen, overal draaien',
    lead: 'Een Kubernetes-omgeving met een keurmerk. Een app die op één Haven-omgeving draait, draait op elke Haven-omgeving, on-premises of in de cloud.',
    bullets: [
      'Haven is een Common Ground-standaard: een vastgestelde Kubernetes-configuratie.',
      'Functioneel identiek, ongeacht de leverancier eronder. Microsoft, Google, AWS, VMware, Red Hat of eigen ijzer.',
      'De volgende minuten lopen we langs het label en langs wat het label invult.',
    ],
    gov: 'Geen vendor lock-in: de overheid kiest de leverancier, niet andersom.',
    link: { href: 'https://haven.commonground.nl/', label: 'haven.commonground.nl' },
    route: '/infra',
    full: true,
  },
  {
    id: 'haven-tag',
    title: 'Haven is een label op de infra',
    lead: 'In de kern is Haven een attest: deze Kubernetes-omgeving voldoet, of nog niet.',
    bullets: [
      'Elke Kubernetes-instance is óf Haven-gecertificeerd óf nog niet, zichtbaar in één oogopslag.',
      'Niet alles is groen: een omgeving die de configuratie nog niet haalt, valt meteen op.',
      'Het keurmerk dwingt overdraagbaarheid af, het is geen vrijblijvend vinkje.',
    ],
    gov: 'Een meetbare eis in plaats van een belofte: het platform bewaakt het, niet de goede bedoeling.',
    route: '/infra/instances',
    highlight: '.rp-page',
  },
  {
    id: 'haven-omgeving',
    title: 'Eén omgeving van dichtbij',
    lead: 'Het platform-productiecluster: gecertificeerd, met de datum waarop het laatst tegen de standaard is gehouden.',
    bullets: [
      'Een app die hier draait, verhuist zonder herschrijven naar elke andere Haven-omgeving.',
      'Het attest staat naast de connectie-info, waar het team toch al kijkt.',
      'Verloopt de certificering, dan weet je het hier als eerste.',
    ],
    gov: 'Herleidbaar en controleerbaar: het attest is data, geen sticker.',
    route: '/infra/instances/k8s-platform-prod',
    highlight: '.rp-haven',
  },
  {
    id: 'haven-plus-monitoring',
    title: 'Haven+ vult de belofte in',
    lead: 'Haven+ levert de productie-bouwstenen die je anders cloud-specifiek zou afnemen. Te beginnen met monitoring.',
    bullets: [
      'Monitoring draait als platformdienst, niet als Azure- of AWS-specifieke functie.',
      'Daardoor blijft de app eronder overdraagbaar tussen Haven-omgevingen.',
      'Het is geen aparte dienst die je los afneemt, het is de laag waar observability al op draait.',
    ],
    gov: 'Minder leveranciersafhankelijkheid op het niveau waar het meestal sluipt: de omliggende diensten.',
    route: '/observability',
    highlight: '.rp-haven-badge',
  },
  {
    id: 'haven-plus-certs',
    title: 'En ook certificaten, secrets en inloggen',
    lead: 'Hetzelfde geldt voor de andere bouwstenen. Certificaten als voorbeeld.',
    bullets: [
      'Certificaten, secrets en authenticatie zijn stuk voor stuk Haven+ platformdiensten.',
      'Vier schermen die het team al kent, nu met hun herkomst zichtbaar: ze draaien op Haven+.',
      'De gebruikskant blijft waar die hoort, de leverende kant is de platformlaag.',
    ],
    gov: 'Eén keer goed geregeld voor de hele overheid, in plaats van per dienst opnieuw uitonderhandeld.',
    route: '/secrets/certificaten',
    highlight: '.rp-haven-badge',
  },
  {
    id: 'digikoppeling-fsc',
    title: 'Digikoppeling en FSC',
    lead: 'Vertrouwde koppelvlakken tussen organisaties.',
    bullets: [
      'Veilig berichten uitwisselen zonder elke keer opnieuw afspraken maken.',
      'Versnipperde bouwstenen als Haven, FSC en OpenZaak, eindelijk verbonden.',
      'De ontbrekende laag die de losse stukken aan elkaar knoopt.',
    ],
    gov: 'Een verbindende platformlaag over bestaande overheidsbouwstenen heen. Daarvoor is mandaat nodig.',
    route: '/koppelvlakken/fsc',
    emit: { type: 'register.connected', title: 'Vertrouwde koppeling via FSC tot stand gebracht' },
    skippable: true,
  },
  {
    id: 'wet-naar-systeem',
    title: 'Wet- en regelgeving uitvoeren',
    lead: 'Een applicatie die een wet of beleidsregel uitvoert, met de wettekst als bron.',
    bullets: [
      'Geharvest uit wetten.overheid.nl, rechtstreeks uit de BWB.',
      'Machine-leesbaar gemaakt, getest en uitgerold.',
      'Bijvoorbeeld de Huurtoeslagwet (BWBR0008659), van tekst naar dienst.',
    ],
    gov: 'De wettekst als single source of truth. Verandert de wet, dan verandert de dienst, herleidbaar.',
    route: '/wetten',
    emit: { type: 'wet.published', title: 'Wet gepubliceerd in het corpus' },
  },
  {
    id: 'wet-draaiende-dienst',
    title: 'Wet of beleid uitvoeren, live',
    lead: 'Van wettekst tot geteste draaiende dienst.',
    bullets: [
      'Selecteer de wet en het platform leidt je naar een werkend systeem.',
      'Regels, tests en uitrol, in één doorlopende flow.',
      'De afstand tussen wetgever en uitvoering wordt klein.',
    ],
    route: '/wetten/nieuw',
    drive: { wizard: 'wet' },
  },
  {
    id: 'algoritmes',
    title: 'Algoritmeregister',
    lead: 'Welke algoritmes nemen besluiten over burgers, en zijn ze verantwoord?',
    bullets: [
      'Elk besluitvormend algoritme staat geregistreerd en uitlegbaar.',
      'Gekoppeld aan de wet die het uitvoert en het team dat het beheert.',
      'Transparantie is wettelijk verplicht, het platform maakt het zichtbaar.',
    ],
    gov: 'Het wettelijk verplichte algoritmeregister, gekoppeld aan de dienst die het draait en de toetsen die het doorstond.',
    route: '/algoritmes',
    emit: { type: 'standard.updated', title: 'Algoritme geregistreerd en beoordeeld' },
    highlight: '.rp-page',
  },
  {
    id: 'verwerkingen',
    title: 'Verwerkingen en DPIA',
    lead: 'Welke persoonsgegevens verwerkt een dienst, en op welke grondslag?',
    bullets: [
      'Het verwerkingenregister komt uit de dienst zelf, niet uit een los Excel.',
      'Een DPIA hangt aan de verwerking en wordt afgedwongen voor productie.',
      'Privacy by design, herleidbaar tot de databron en de wet.',
    ],
    gov: 'Het AVG-verwerkingenregister als levend onderdeel van het platform, niet als jaarlijkse papieren exercitie.',
    route: '/verwerkingen',
    emit: { type: 'compliance.dropped', title: 'Productie geblokkeerd: DPIA ontbreekt' },
    highlight: '.rp-page',
  },
  {
    id: 'openbaarheid',
    title: 'Woo en archivering',
    lead: 'Openbaar maken en archiveren als ingebouwde functie, niet als handwerk.',
    bullets: [
      'Wat onder de Woo valt is al voorbereid op publicatie.',
      'Archivering volgens de Archiefwet, automatisch en herleidbaar.',
      'Transparantie is de norm, niet een verzoek dat maanden duurt.',
    ],
    gov: 'Woo en Archiefwet ingebakken in het gebaande pad, niet als losse afdeling die achteraf opruimt.',
    route: '/openbaarheid',
    emit: { type: 'standard.updated', title: 'Document gepubliceerd onder de Woo' },
    highlight: '.rp-page',
    skippable: true,
  },
  {
    id: 'toegankelijkheid',
    title: 'Toegankelijkheid, afgedwongen',
    lead: 'WCAG 2.2 AA als check in de pijplijn, niet als verklaring achteraf.',
    bullets: [
      'Elke dienst heeft een toegankelijkheidsverklaring die klopt met de werkelijkheid.',
      'Het NL Design System levert toegankelijke bouwstenen by default.',
      'Faalt de check, dan haalt de dienst de productie-gate niet.',
    ],
    gov: 'EN 301 549 en WCAG zijn wettelijk verplicht. Het platform toetst ze automatisch in plaats van achteraf.',
    route: '/toegankelijkheid',
    emit: { type: 'compliance.dropped', title: 'Toegankelijkheidscheck gezakt, gate dicht' },
    highlight: '.rp-page',
    skippable: true,
  },
  {
    id: 'llm-afnemen',
    title: 'Soevereine LLM, live',
    lead: 'Een AI-sleutel afnemen die binnen het Rijk blijft.',
    bullets: [
      'Kies een model, een team en het doel, en de gateway regelt de rest.',
      'Prompts en data verlaten de eigen omgeving niet.',
      'AI als platformdienst, met classificatie en herkomst ingebouwd.',
    ],
    gov: 'Een eigen LLM-gateway: geen overheidsdata naar een model van een ander.',
    route: '/ai/llm',
    drive: { wizard: 'llm' },
  },
  {
    id: 'ai-skills',
    title: 'AI en skills',
    lead: 'Code wordt goedkoper, zelf bouwen aantrekkelijker.',
    bullets: [
      'AI maakt zelf bouwen goedkoper dan ooit.',
      'Maar alleen veilig met een goed platform eronder.',
      'Ruig terrein wordt begaanbaar, bergen worden heuvels.',
    ],
    route: '/ai/skills',
    emit: { type: 'ai.skill.installed', title: 'Skill geïnstalleerd voor het team' },
    skippable: true,
  },
  {
    id: 'platform-als-product',
    title: 'Platform als product',
    lead: 'De begane grond waar iedereen op bouwt.',
    bullets: [
      'Een platform is geen project dat af is, maar een product dat blijft.',
      'Het vergt mandaat en structurele financiering, geen eenmalig budget.',
      'Goed gereedschap trekt goed vakmanschap aan, en houdt het binnen.',
    ],
    route: '/',
    emit: { type: 'deploy.completed', title: 'Platform-release uitgerold' },
  },
  {
    id: 'wrap-up',
    title: 'Dank',
    lead: 'De overheid is een techbedrijf. Laten we ons ook zo organiseren.',
    bullets: [
      'Platform engineering: de gedeelde basislaag waarop teams bouwen.',
      'Begane Grond liet zien hoe dat er voor de Rijksoverheid uit kan zien.',
    ],
    link: { href: 'https://anneschuth.nl', label: 'anneschuth.nl' },
    full: true,
  },
];
