// Mock content for the docs hub: a searchable list of runbooks, guides and
// reference pages. This is demo data local to the "Leren" domain (no store
// dependency) so the docs hub feels populated and searchable. Each entry has a
// kind (runbook|guide|referentie), a category, an estimated reading time and a
// few keywords so the search field matches on more than just the title.
export const docs = [
  {
    id: 'doc-newdev',
    title: 'Aan de slag als nieuwe developer',
    kind: 'guide',
    category: 'Onboarding',
    minutes: 12,
    icon: 'person-circle',
    updated: '3 dagen geleden',
    summary: 'Van rijksaccount tot je eerste merge: werkplek, toegang, repo en lokale omgeving.',
    keywords: ['onboarding', 'account', 'werkplek', 'repo', 'git', 'eerste pr'],
  },
  {
    id: 'doc-golden-path',
    title: 'Golden path: nieuwe service opzetten',
    kind: 'guide',
    category: 'Applicaties',
    minutes: 9,
    icon: 'rectangle-stack',
    updated: '1 week geleden',
    summary: 'Genereer een service uit een template, koppel infra en krijg CI in één keer groen.',
    keywords: ['golden path', 'template', 'steiger', 'scaffold', 'service', 'ci', 'app'],
  },
  {
    id: 'doc-runbook-incident',
    title: 'Runbook: incident afhandelen (sev1/sev2)',
    kind: 'runbook',
    category: 'Operatie',
    minutes: 7,
    icon: 'exclamation-triangle',
    updated: 'gisteren',
    summary: 'Stappenplan bij een productieverstoring: erkennen, mitigeren, communiceren, evalueren.',
    keywords: ['incident', 'sev1', 'sev2', 'piket', 'on-call', 'postmortem'],
  },
  {
    id: 'doc-runbook-rotate',
    title: 'Runbook: secret roteren',
    kind: 'runbook',
    category: 'Security',
    minutes: 4,
    icon: 'lock-closed',
    updated: '4 dagen geleden',
    summary: 'Roteer een DB-wachtwoord of API-key zonder downtime en log de wijziging.',
    keywords: ['secret', 'roteren', 'vault', 'api-key', 'wachtwoord'],
  },
  {
    id: 'doc-promote',
    title: 'Runbook: promoten naar productie',
    kind: 'runbook',
    category: 'Operatie',
    minutes: 5,
    icon: 'arrow-up-arrow-down',
    updated: '2 dagen geleden',
    summary: 'Promoot een release van acceptatie naar productie via de omgevingen-pijplijn.',
    keywords: ['promote', 'release', 'prod', 'deploy', 'omgevingen'],
  },
  {
    id: 'doc-wcag',
    title: 'Toegankelijkheid (WCAG 2.2 AA) voor frontend',
    kind: 'guide',
    category: 'Standaarden',
    minutes: 15,
    icon: 'eye',
    updated: '1 week geleden',
    summary: 'Hoe je met het NLDD design system aantoonbaar aan WCAG 2.2 AA voldoet.',
    keywords: ['wcag', 'toegankelijkheid', 'a11y', 'nldd', 'pa11y', 'contrast'],
  },
  {
    id: 'doc-opensource',
    title: 'Open source werken: open-tenzij',
    kind: 'guide',
    category: 'Standaarden',
    minutes: 10,
    icon: 'folder-stack',
    updated: '5 dagen geleden',
    summary: 'EUPL-1.2, een nette README, CONTRIBUTING.md en geen secrets in de geschiedenis.',
    keywords: ['open source', 'eupl', 'open-tenzij', 'licentie', 'contributing', 'publiceren'],
  },
  {
    id: 'doc-bio',
    title: 'Security-baseline (BIO) in de praktijk',
    kind: 'guide',
    category: 'Standaarden',
    minutes: 18,
    icon: 'shield-check-mark',
    updated: '2 weken geleden',
    summary: 'De BIO-controls die elke dienst raken: encryptie, logging, toegang en patch-status.',
    keywords: ['bio', 'security', 'baseline', 'encryptie', 'logging', 'patch'],
  },
  {
    id: 'doc-cli',
    title: 'De rp-CLI installeren en inloggen',
    kind: 'referentie',
    category: 'Tooling',
    minutes: 6,
    icon: 'terminal',
    updated: '6 dagen geleden',
    summary: 'Installeer de rp-CLI, log in met je rijksaccount en koppel je standaardteam.',
    keywords: ['cli', 'rp', 'terminal', 'login', 'installatie', 'tooling'],
  },
  {
    id: 'doc-infra',
    title: 'Infra afnemen uit de servicecatalogus',
    kind: 'guide',
    category: 'Infrastructuur',
    minutes: 8,
    icon: 'cloud',
    updated: '3 dagen geleden',
    summary: 'Bestel Postgres, Kafka of een cluster en koppel het aan je app en team.',
    keywords: ['infra', 'catalogus', 'postgres', 'kafka', 'kubernetes', 'afnemen'],
  },
  {
    id: 'doc-api-adr',
    title: 'API Design Rules (ADR) toepassen',
    kind: 'referentie',
    category: 'Koppelvlakken',
    minutes: 11,
    icon: 'link',
    updated: '1 week geleden',
    summary: 'De NL GOV API Design Rules met de Spectral-linter aantoonbaar naleven.',
    keywords: ['adr', 'api', 'design rules', 'spectral', 'openapi', 'koppelvlak'],
  },
  {
    id: 'doc-llm',
    title: 'Soevereine LLM-gateway gebruiken',
    kind: 'guide',
    category: 'AI',
    minutes: 9,
    icon: 'sparkles',
    updated: '4 dagen geleden',
    summary: 'Roep het Overheids-LLM aan met de juiste classificatie en data-residentie.',
    keywords: ['llm', 'ai', 'gateway', 'soeverein', 'classificatie', 'residentie'],
  },
];

// Government-standards learning paths. These complement the store.learningPaths
// (which are the operational onboarding tracks) with curriculum-style tracks
// focused on compliance themes. Each module links into the relevant standard or
// runbook elsewhere in the platform.
export const standardsPaths = [
  {
    id: 'sp-a11y',
    name: 'Toegankelijkheid bouwen',
    standard: 'WCAG 2.2 AA',
    accent: 'accent',
    icon: 'eye',
    lede: 'Lever een frontend die aantoonbaar voor iedereen werkt, inclusief screenreaders en toetsenbordnavigatie.',
    badge: 'Digitoegankelijk',
    to: '/standaarden',
    modules: [
      { title: 'Waarom toegankelijkheid verplicht is (EN 301 549)', done: true, minutes: 8 },
      { title: 'NLDD-componenten met de juiste semantiek', done: true, minutes: 12 },
      { title: 'Kleurcontrast en focus-states', done: true, minutes: 10 },
      { title: 'pa11y in de CI-pijplijn', done: false, minutes: 9 },
      { title: 'Een toegankelijkheidsverklaring opstellen', done: false, minutes: 14 },
    ],
  },
  {
    id: 'sp-security',
    name: 'Veilig ontwikkelen',
    standard: 'BIO',
    accent: 'critical',
    icon: 'shield-check-mark',
    lede: 'Pas de Baseline Informatiebeveiliging Overheid toe op je code, je pijplijn en je infra.',
    badge: 'BIO-baseline',
    to: '/security',
    modules: [
      { title: 'Dreigingsmodellering voor je dienst', done: true, minutes: 15 },
      { title: 'Secrets buiten je repository houden', done: true, minutes: 7 },
      { title: 'Dependency- en CVE-scanning', done: false, minutes: 10 },
      { title: 'Encryptie in transit en at rest', done: false, minutes: 12 },
      { title: 'Logging en audittrail volgens BIO', done: false, minutes: 11 },
    ],
  },
  {
    id: 'sp-opensource',
    name: 'Open source publiceren',
    standard: 'Open-tenzij',
    accent: 'success',
    icon: 'folder-stack',
    lede: 'Publiceer je broncode open volgens het rijksbeleid open-tenzij, met de juiste licentie en hygiëne.',
    badge: 'EUPL-1.2',
    to: '/code',
    modules: [
      { title: 'Het open-tenzij-afwegingskader', done: true, minutes: 9 },
      { title: 'EUPL-1.2 toevoegen aan je repo', done: true, minutes: 5 },
      { title: 'README, CONTRIBUTING en Code of Conduct', done: false, minutes: 13 },
      { title: 'Repo schoonmaken: geen secrets in history', done: false, minutes: 8 },
      { title: 'Publiceren op code.overheid.nl', done: false, minutes: 6 },
    ],
  },
];
